### ISSUE TITLE
font awesome name="loading" not working

### ISSUE THREAD

**Issue by gpalomar** [picardy/angular-fontawesome#11]
This code doesn't work.
`<fa name="loading" spin ng-style="{'color': checkColor}"></fa>`

Did you want to use name="spinner"?
`<fa name="spinner" spin></fa>`works

**Comment by fastfrwrd** [comment]
wow! gross oversight there. fixing now.

**Comment by fastfrwrd** [comment]
Thanks for opening that issue!

**Comment by gpalomar** [comment]
nice directive ;)
