### ISSUE TITLE
font-awesome remove `css` from bower main.

### ISSUE THREAD

**Issue by zhuangya** [picardy/angular-fontawesome#13]
font-awesome removed `css` from bower main in [this commit](https://github.com/FortAwesome/Font-Awesome/commit/7cde41ea934f43e66dc123ea6411d8535b50a4f7)

i understand that this is an upstream problem, but it would be better if `angular-fontawesome` can override `font-awsome`'s bower main to `css/font-awesome.css`

otherwise, anyone who install `angular-fontawesome` via bower, would not see any icons on their pages, especially ones use `wiredep`.

i'm just suggesting here. feel free to close this if you think it's non-sense

**Comment by fastfrwrd** [comment]
Hey there,

This project is focused on utilities for creating a component at the view layer of your Angular app and tries not to have an opinion about how the font-aweome CSS got loaded. As such, we probably shouldn't include any CSS in our bower.json.
