### ISSUE TITLE
Is posible to use them in a controller?

### ISSUE THREAD

**Issue by coolfarmer** [picardy/angular-fontawesome#14]
Is possible to use them in a controller? Because it's not working or i'm forget something.

    DTColumnBuilder.newColumn('share_on_facebook').withTitle('Share on Facebook').renderWith(function(data, type, full) {
      if (typeof full.share_on_facebook !== 'undefined') {
        return '<fa name="check"></fa>';
      } else {
        return '<fa name="times"></fa>';
      }
    }),

Thanks.

**Comment by fastfrwrd** [comment]
You're probably missing the compile step - do other directives (for example ng-show) work when you use this form?

**Comment by fastfrwrd** [comment]
Oh - I just saw how old this is. Sorry for the delay - I'm going to close this given its age, please comment back if you're still having trouble.
