### ISSUE TITLE
What version of FontAwesome is this wrapper using?

### ISSUE THREAD

**Issue by JFSolorzano** [picardy/angular-fontawesome#15]
This is a question.

**Comment by fastfrwrd** [comment]
You can use whatever 4.x version you want. The new demo harness loads the latest version, but angular-fontawesome expects you to load fontawesome yourself. This is just a directive to help you avoid boilerplate code and make it easy to make dynamic icon widgets in Angular.

**Comment by JFSolorzano** [comment]
Oh i see
