### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by TheSharpieOne** [picardy/angular-fontawesome#23]
The latest version on npm is 0.4.0, the current version is 1.0.0.  Please `npm publish` to update npm.

https://www.npmjs.com/package/angular-fontawesome

**Comment by neeckeloo** [comment]
👍

**Comment by tuckbick** [comment]
Sorry this took so long! Enjoy using the name `@picardy/angular-fontawesome`.

**Comment by tuckbick** [comment]
Alright, after some finagling, 1.0.0 should be available under the original name `angular-fontawesome`. Let us know if y'all have any issues pulling it down!
