### ISSUE TITLE
Publish as an NPM module

### ISSUE THREAD

**Issue by DaleJefferson** [picardy/angular-fontawesome#6]
AngularJS is now available as a NPM module it would be great if I could install angular-fontawesome in the same way.

**Comment by fastfrwrd** [comment]
good deal - will get this looked at ASAP.

**Comment by fastfrwrd** [comment]
https://www.npmjs.com/package/angular-fontawesome

Let me know if anything doesn't work, I haven't really tried out using npm/browerify type setups before.

**Comment by DaleJefferson** [comment]
Perfect, thanks for the great directive.
