### ISSUE TITLE
include module error

### ISSUE THREAD

**Issue by HoplaGeiss** [picardy/angular-fontawesome#8]
I just started using bower and angular..
It seems I can't instantiate angular-fontawesome module.
It is most probably a stupid mistake on my part :/

Here is my bower.json file

![screenshot from 2015-03-16 21 08 43](https://cloud.githubusercontent.com/assets/5755785/6675494/092eefdc-cc21-11e4-92f7-1e1390b4a1ce.png)

And part of my app,js file, am I doing something wrong ?
![screenshot from 2015-03-16 21 11 58](https://cloud.githubusercontent.com/assets/5755785/6675517/2ad7bde4-cc21-11e4-9577-63558c5d4abc.png)

**Comment by fastfrwrd** [comment]
I've got to admit that this syntax all looks a little weird to me (the "lib" and "vendor" thing specifically. Were you able to make any progress? Also, please copy the error.

**Comment by HoplaGeiss** [comment]
Sorry I forgot I opened this issue. Yeah I found what I did wrong. It is all because of the asset pipeline in rails. 
I added this line to my config/application.rb

```
config.assets.paths << Rails.root.join("lib","assets","bower_components");
```

And also in application.js and aplication.scss I made sure to have the full path of angular font-awesome!

**Comment by fastfrwrd** [comment]
Glad everything worked out - enjoy angular-fontawesome!
