### ISSUE TITLE
Enchancement: for READ-ME

### ISSUE THREAD

**Issue by Gregory-Phillips** [picardy/angular-fontawesome#9]
Thanks for taking the time to create this angular module. I finally got it up and running. It took me a bit but I realized that I needed to include the native `fontawesome.css` for this to work. Kinda a no brainer after I realized this but it might help to document this in the `READ-ME` for others.

**Comment by fastfrwrd** [comment]
Thanks for using the project! I'll try to tackle this this weekend.
